sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

branches:
  only:
    - ci

install:
  - git clone https://github.com/malston/spring-boot-graph-processing-example.git build
  - ./build/integration-test/integration-test.sh

script:
  - ./build/integration-test/build.sh
